version: '3'

services:

#######################################################
###                   HUGINN                        ###
#######################################################

  huginn:  
    image: huginn/huginn
    restart: always
    environment:
      - VIRTUAL_HOST=huginn.mpdmail.net
      - LETSENCRYPT_HOST=huginn.mpdmail.net,cloud.mpdmail.net
      - LETSENCRYPT_EMAIL=github@mpdmail.de
      - HUGINN_DATABASE_USERNAME=huginn
      - HUGINN_DATABASE_ADAPTER=postgresql
      - POSTGRES_PORT_5432_TCP_ADDR=huginn_postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
    ports:
      - "3000:3000"
    networks:
      - proxy-tier
      - huginn_net
    depends_on:
      - huginn_postgres
    env_file:
      - credentials.env

  huginn_postgres:
    image: postgres:10.2
    restart: always
    environment:
      - POSTGRES_USER=huginn
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - credentials.env
    networks:
      - huginn_net

#######################################################

#######################################################
###                NEXTCLOUD                        ###
#######################################################


  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - nextcloud_db:/var/lib/mysql
    env_file:
      - credentials.env
    networks:
      - nextcloud_net

  nextcloud_app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=cloud.mpdmail.net
      - LETSENCRYPT_HOST=huginn.mpdmail.net,cloud.mpdmail.net
      - LETSENCRYPT_EMAIL=github@mpdmail.de
      - MYSQL_HOST=nextcloud_db
    env_file:
      - credentials.env
    depends_on:
      - nextcloud_db
    networks:
      - proxy-tier
      - nextcloud_net
      - default

  nextcloud_cron:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
    networks:
      - nextcloud_net


#######################################################
###                NGINX-PROXY                      ###
#######################################################

  proxy:
    build: ./proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

#######################################################


volumes:
  nextcloud_db:
  nextcloud:
  certs:
  conf.d:
  vhost.d:
  html:
  postgres-data:

networks:
  proxy-tier:
  huginn_net:
  nextcloud_net:
