version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: mysqld --max-connections=1000
    volumes:
      - db:/var/lib/mysql
    env_file:
      - credentials_nextcloud.env

  redis:
    image: redis
    restart: always

  app:  
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=cloud.mpdmail.de,cloud.mpdmail.net
      - MYSQL_HOST=db
    env_file:
      - credentials_nextcloud.env
      - ../certificate.env
    depends_on:
      - db
      - redis

  cron:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:

networks:
  default:
    external:
      name: nginx-proxy
